# A sample Guardfile
# More info at https://github.com/guard/guard#readme

guard 'sass', :input => 'scss', :output => 'css'

guard 'livereload' do
  watch(%r{js/.+\.js})
  watch(%r{scss/.+\.scss$})
  watch(%r{pages/.+\.xsl$})
  watch(%r{utilities/.+\.xsl$})
end
